### ISSUE TITLE
NoodleExtensions won't load

### ISSUE THREAD

**Issue by lordlad** [StackDoubleFlow/NoodleExtensions#26] opened 2022-08-20 07:41 UTC
Installed the latest version of NoodleExtensions over the last one (v1.2.2 to v1.2.3) and now it won't loaded with the following error:

"libnoodleextensions.so didn't load because dlopen failed - cannot locate symbol
![com beatgames beatsaber-20220820-152700](https://user-images.githubusercontent.com/2647193/185734702-74ab146c-48d0-4631-b7e7-0dc4954cc492.jpg)
"

**Comment by Fernthedev** [comment] 2022-08-20 14:47
Duplicate of bsq-ports/Chroma#21

**Closed by Fernthedev** 2022-08-20 14:47 UTC
