### ISSUE TITLE
String Array Tracks crash the game

### ISSUE THREAD

**Issue by TheZipCreator** [StackDoubleFlow/NoodleExtensions#9] opened 2022-03-06 13:33 UTC
In some maps, objects are assigned multiple tracks simultaneously with an array of strings. Example:
```
{
  "_time" : 60.5,
  "_lineIndex" : 3,
  "_lineLayer" : 1,
  "_type" : 1,
  "_cutDirection" : 5,
  "_customData" : {
    "_noteJumpStartBeatOffset" : 16,
    "_track" : [
      "flickNote",
      "trackAssembleintro60.5"
    ]
  }
}
```
This note would be assigned to track `flickNote` and track `trackAssembleinto60.5` at the same time.

Currently, this will crash the game. This behavior isn't technically documented on the Heck wiki but it's intended, or so I've been told.

**Comment by Fernthedev** [comment] 2022-03-06 13:36
Do you happen to have the map key or a test map for this? I know this is a supported feature and I had initially added support for it but with lack of testing I just assumed it would work:tm: 
Appreciate the extensive bug report and details :)

**Comment by TheZipCreator** [comment] 2022-03-06 13:40
https://beatsaver.com/maps/2012a this map. I assume it's the multi-track feature that's the issue here because the other crashes I've had with noodle maps were due to environment removals (for some reason removing certain environment objects crashed the game when a note was spawned), and the only other thing that this map does that other maps don't is the multi-track thing. I'll be honest I haven't constructed an isolated example to test this with, so I'm only like 80% sure that this is the issue, as I can't see what else could be causing it (I've tried disabling environment removal on that map and it still crashed).

**Comment by Fernthedev** [comment] 2022-03-06 13:48
Environment removal is a Chroma feature, it does not ever depend on Noodle. The only Noodle feature that can affect it is parenting but that wouldn't cause a crash either.

As for the crash in the map, I could not reproduce it so I'll be closing the issue for the time being.

**Closed by Fernthedev** 2022-03-06 13:48 UTC
Labels: bug, question
