### ISSUE TITLE
no arrows in game modifier doesn't function properly if NoodleExtensions is on

### ISSUE THREAD

**Issue by princessluna123** [StackDoubleFlow/NoodleExtensions#25] opened 2022-08-19 17:57 UTC
If NoodleExtensions is turned on, the no arrows in game modifier doesn't work. It only works if you turn off the Jsondata core mod.

**Comment by Fernthedev** [comment] 2022-08-19 17:57
Duplicate of bsq-ports/Chroma#16
Fixed already

**Closed by Fernthedev** 2022-08-19 17:57 UTC
