### ISSUE TITLE
Some objects don't have correct luminescence

### ISSUE THREAD

**Issue by JonnyVR1** [StackDoubleFlow/NoodleExtensions#27] opened 2022-08-20 18:36 UTC
@Fernthedev Example map - Mitis - Homesick, lyrical text doesn't display as it does on the PC version of the mod

**Comment by Fernthedev** [comment] 2022-08-20 18:38
What does luminescence mean in this instance? Could you provide an example?
Might be a duplicate of #22

**Comment by JonnyVR1** [comment] 2022-08-20 18:39
Also the flower rendered in the middle in the chorus looks off on the quest version, I suspect the same issue

**Comment by JonnyVR1** [comment] 2022-08-20 18:46
Tricky to get screenshots of the lyrics, this is the best I could do for now

![com beatgames beatsaber-20220820-193939](https://user-images.githubusercontent.com/949967/185761859-6abc9b31-9bbb-40ef-8756-746d45bb975e.jpg)
![com beatgames beatsaber-20220820-194043](https://user-images.githubusercontent.com/949967/185761877-d7b744a9-b724-440d-8646-01a3a105f558.jpg)
![com beatgames beatsaber-20220820-194125](https://user-images.githubusercontent.com/949967/185761883-c701bbe5-40a5-4c96-8924-53805c112f44.jpg)

**Comment by Fernthedev** [comment] 2022-08-20 19:35
That would be the new algorithm for choosing material color (yes I changed it for the third time) and wall borders not working.
The algorithm can be switched in noodle settings. 
Will be closing this issue as it's technically not a bug, though I do understand the fact that it does look worse. I'm not really sure how to improve it though

**Closed** 2022-08-20 19:35 UTC

**Comment by JonnyVR1** [comment] 2022-08-20 20:18
Whilst the algorithm can be changed, none of the 3 options render the flower correctly so I would actually consider this a bug.

**Comment by Fernthedev** [comment] 2022-08-20 20:20
Well there is no true "correct" visual for the flower since there are no distortions and bloom (by default)
You'll have to see if wall borders would improve the visual or if the graphical settings mentioned above show the proper visual. 
If you have a better algorithm in mind, you can PR it as a setting and if it's good enough, maybe become the default. Look at ObstacleController.ManualUpdate

**Comment by Zayne42** [comment] 2022-08-21 19:23
will this eb fixed in the next update?
