### ISSUE TITLE
Having the Noodle mod causes playability issues with 360/90 degree maps

### ISSUE THREAD

**Issue by LaidBackAries** [StackDoubleFlow/NoodleExtensions#57] opened 2023-10-24 15:53 UTC
While playing 360/90 degree maps, the lane lights/triangles don't light up so blocks will come from surprise locations when Noodle (and/or Chroma) is installed as as a mod. They both come with the the file "Tracks" so i suspect that's where the conflict is. Previously, I only using one at a time and discovered this to be the case after recently installing Noodle (after I stopped using Chroma). To be clear, I'm playing non-noodle maps here. It's a bigger issue with a Chroma since it's used to light maps but it is affected by Noodle as well, so here's my official report on it. :) 
Standalone Quest modded 1.28

**Comment by Fernthedev** [comment] 2023-11-01 17:27
Duplicate of https://github.com/StackDoubleFlow/CustomJSONData/issues/35

**Closed by Fernthedev** 2023-11-01 17:27 UTC
